#!/usr/bin/env python3
"""Convert a course spec (holes.json) into the Luau ModuleScript the CourseBuilder reads.

  python3 tools/holes_to_lua.py                 # write src/ServerStorage/CourseData/LanternGrove.luau
  python3 tools/holes_to_lua.py --push          # ...and copy it into Studio (Edit mode)
  python3 tools/holes_to_lua.py --push --build  # ...and rebuild workspace.Course from it (one-step re-import)

The spec lives in assets/vr-mini-golf/lantern-grove/holes.json (Game Art Bot). The module is a plain Lua table with
the same structure (JSON arrays -> 1-based Lua arrays, null -> nil), plus a `source` block with the file's sha1.
Only ever talks to the Studio whose name contains run_playtests.PLACE_ID.
"""
import argparse
import hashlib
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GAME_DIR = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(GAME_DIR))
DEFAULT_SPEC = os.path.join(REPO, "assets", "vr-mini-golf", "lantern-grove", "holes.json")
DEFAULT_OUT = os.path.join(GAME_DIR, "src", "ServerStorage", "CourseData", "LanternGrove.luau")

IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
LUA_KEYWORDS = {"and", "break", "do", "else", "elseif", "end", "false", "for", "function", "if", "in", "local", "nil",
                "not", "or", "repeat", "return", "then", "true", "until", "while", "continue", "type"}


def lua_str(s):
    return json.dumps(s, ensure_ascii=False)


def num(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    r = repr(float(v))
    return r[:-2] if r.endswith(".0") else r


def to_lua(v, indent=0):
    pad = "\t" * indent
    if v is None:
        return "nil"
    if isinstance(v, (bool, int, float)):
        return num(v)
    if isinstance(v, str):
        return lua_str(v)
    if isinstance(v, list):
        if all(isinstance(x, (int, float)) and not isinstance(x, bool) for x in v):
            return "{ " + ", ".join(num(x) for x in v) + " }" if v else "{}"
        if not v:
            return "{}"
        inner = ",\n".join(pad + "\t" + to_lua(x, indent + 1) for x in v)
        return "{\n" + inner + ",\n" + pad + "}"
    if isinstance(v, dict):
        items = [(k, x) for k, x in v.items() if x is not None]
        if not items:
            return "{}"
        parts = []
        for k, x in items:
            key = k if IDENT.match(k) and k not in LUA_KEYWORDS else "[" + lua_str(k) + "]"
            parts.append(pad + "\t" + key + " = " + to_lua(x, indent + 1))
        flat = "{ " + ", ".join(p.strip() for p in parts) + " }"
        if len(flat) + len(pad) < 120 and "\n" not in flat:
            return flat
        return "{\n" + ",\n".join(parts) + ",\n" + pad + "}"
    raise TypeError(type(v))


def convert(spec_path):
    raw = open(spec_path, "rb").read()
    data = json.loads(raw)
    sha = hashlib.sha1(raw).hexdigest()
    rel = os.path.relpath(spec_path, REPO)
    # schema prose is long and only for humans; keep the version
    data = dict(data)
    schema = data.pop("schema", {})
    data["source"] = {"file": rel, "sha1": sha, "schemaVersion": schema.get("version")}
    # hole-in-one lines from the designer's hNN-notes.md (aim = atan2(dz, dx) in degrees, speed studs/s, mover phase s)
    spec_dir = os.path.dirname(spec_path)
    for h in data.get("holes", []):
        notes = os.path.join(spec_dir, "h%02d-notes.md" % h["number"])
        if not os.path.exists(notes):
            continue
        txt = open(notes).read()
        m = re.search(r"aim \*\*([\d.]+)°\*\*.*?speed \*\*([\d.]+) studs/s\*\*(?:[^.]*?start phase t=([\d.]+)s)?", txt, re.S)
        if m:
            h["hio"] = {"aim_deg": float(m.group(1)), "speed": float(m.group(2)),
                        "phase": float(m.group(3)) if m.group(3) else None, "from": os.path.basename(notes)}
    head = ("-- GENERATED by games/vr-mini-golf/tools/holes_to_lua.py from %s (sha1 %s).\n"
            "-- Do not edit by hand: edit the JSON spec and regenerate (python3 tools/holes_to_lua.py --push --build).\n"
            "-- Units: studs, Y up, per-hole local frames (see the spec's schema block). Read by ServerStorage.CourseBuilder.\n"
            % (rel, sha[:12]))
    return head + "return " + to_lua(data) + "\n", data


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--spec", default=DEFAULT_SPEC)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--push", action="store_true", help="copy the module into Studio (Edit)")
    ap.add_argument("--build", action="store_true", help="run CourseBuilder.Build() in Studio afterwards")
    args = ap.parse_args()
    src, data = convert(args.spec)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as fh:
        fh.write(src)
    holes = data.get("holes", [])
    print("wrote %s (%d bytes, %d holes, par %s)" % (os.path.relpath(args.out, GAME_DIR), len(src), len(holes),
                                                      sum(h["par"] for h in holes)))
    if args.push or args.build:
        sys.path.insert(0, HERE)
        import run_playtests as rp  # noqa: E402
        st = rp.Studio()
        if st.mode()[0] != "Edit":
            raise SystemExit("stop play first")
        if args.push:
            ns = argparse.Namespace(files=[args.out])
            rp.cmd_push(ns, st)
        if args.build:
            r = st.luau("local CB = require(game.ServerStorage.CourseBuilder:Clone())\n"
                        "return CB.Build(require(game.ServerStorage.CourseData.LanternGrove:Clone()))", "Edit", timeout=600)
            print("build:", r)


if __name__ == "__main__":
    main()
