#!/usr/bin/env python3
"""Convert the Lantern Grove world map (world.json) into the WorldLayout ModuleScript the CourseBuilder reads.

  python3 tools/world_to_lua.py                 # write src/ServerStorage/CourseData/WorldLayout.luau
  python3 tools/world_to_lua.py --push          # ...and copy it into Studio (Edit mode)
  python3 tools/world_to_lua.py --push --build  # ...and rebuild workspace.Course with it

world.json (Game Art Bot, assets/vr-mini-golf/lantern-grove/world/) places every hole of holes.json in one big
world: `holes[n].placement = {origin = {x, y, z}, yaw_deg}`. The builder applies
    holeCF = CFrame.new(origin) * CFrame.Angles(0, rad(yaw_deg), 0);  part.CFrame = holeCF * localCFrame
to every hole element (felt, walls, movers, hazards, teleports, tee, cup, decor), so a new layout never touches the
hole geometry: edit world.json (or the generated module), regenerate, rebuild.
Without a WorldLayout module (or with `enabled = false`) the builder falls back to the flat greybox layout
(holes.json world_offset/world_yaw + 8 studs).

The terrain recipe/heightmap is not copied here (too big): tools/world_terrain.py writes the Terrain from
terrain-4stud.json.
"""
import argparse
import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from holes_to_lua import GAME_DIR, REPO, to_lua  # noqa: E402

DEFAULT_WORLD = os.path.join(REPO, "assets", "vr-mini-golf", "lantern-grove", "world", "world.json")
DEFAULT_OUT = os.path.join(GAME_DIR, "src", "ServerStorage", "CourseData", "WorldLayout.luau")
KEEP = ["name", "version", "bounds", "spawn", "holes", "stream", "mill_flume", "lakes", "waterfalls", "paths",
        "hollow_tree", "pois", "lanterns", "backdrop"]


def convert(path):
    raw = open(path, "rb").read()
    world = json.loads(raw)
    sha = hashlib.sha1(raw).hexdigest()
    rel = os.path.relpath(path, REPO)
    out = {"enabled": True, "source": {"file": rel, "sha1": sha}}
    for k in KEEP:
        if k in world:
            out[k] = world[k]
    # holes: keyed by number, only what the builder needs (the rest is for humans)
    out["holes"] = {}
    for h in world["holes"]:
        out["holes"][str(h["number"])] = {
            "origin": h["placement"]["origin"],
            "yaw": h["placement"]["yaw_deg"],
            "pad_ground_y": h.get("pad_ground_y"),
            "zone": h.get("zone"),
        }
    src = to_lua(out)
    # string keys "1".."9" -> numeric keys so layout.holes[n] works
    for n in range(1, 20):
        src = src.replace('["%d"] = ' % n, "[%d] = " % n)
    head = ("-- GENERATED by games/vr-mini-golf/tools/world_to_lua.py from %s (sha1 %s).\n"
            "-- Per-hole world placement (origin + yaw) and world features for ServerStorage.CourseBuilder.\n"
            "-- Edit world.json (or set enabled = false for the flat greybox layout) and rebuild:\n"
            "--   python3 tools/world_to_lua.py --push --build\n" % (rel, sha[:12]))
    return head + "return " + src + "\n", out


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--world", default=DEFAULT_WORLD)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--push", action="store_true")
    ap.add_argument("--build", action="store_true")
    args = ap.parse_args()
    src, data = convert(args.world)
    with open(args.out, "w") as fh:
        fh.write(src)
    print("wrote %s (%d bytes, %d holes)" % (os.path.relpath(args.out, GAME_DIR), len(src), len(data["holes"])))
    if args.push or args.build:
        import run_playtests as rp  # noqa: E402
        st = rp.Studio()
        if st.mode()[0] != "Edit":
            raise SystemExit("stop play first")
        if args.push:
            rp.cmd_push(argparse.Namespace(files=[args.out]), st)
        if args.build:
            r = st.luau("local CB = require(game.ServerStorage.CourseBuilder:Clone())\n"
                        "return CB.Build(require(game.ServerStorage.CourseData.LanternGrove:Clone()))", "Edit", timeout=900)
            print("build:", r)


if __name__ == "__main__":
    main()
