"""Turn export/*_rig.json into the RobotRigs Luau module used by RobotBuilder.
Root size, hip height and hit capsule are fixed per robot (copied from the robots they replaced) so gameplay
balance doesn't depend on the mesh silhouette.

Run: python3 gen_rigs.py [out.luau]   (default: ../RobotRigs.luau, symlinked into rca-work)
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
EXPORT = os.path.join(HERE, "..", "export")
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser(
    os.path.join(HERE, "..", "RobotRigs.luau"))

FIXED = {
    "Scout": {"root": (3, 3, 2.5), "hip": 2.6, "hit": (1.91, 2.19, 2.04)},
    "Kitsune": {"root": (2.6, 3, 2.2), "hip": 3.6, "hit": (1.90, 3.20, 2.97)},
    "Aero": {"root": (3.6, 3, 3), "hip": 2.2, "hit": (2.40, 1.30, 1.25)},
}


def num(v):
    s = ("%.3f" % v).rstrip("0").rstrip(".")
    return s if s not in ("-0", "") else "0"


def vec(v):
    return "Vector3.new(%s)" % ", ".join(num(x) for x in v)


lines = ["-- Generated by assets/robo-clash-arena/blender/gen_rigs.py from export/*_rig.json. Do not edit by hand.",
         "-- Coordinates: robot standing on y = 0 facing -Z (same space as the imported meshes).",
         "return {"]
for rid, fx in FIXED.items():
    d = json.load(open(os.path.join(EXPORT, rid.lower() + "_rig.json")))
    lines.append("\t%s = {" % rid)
    lines.append("\t\tTris = %d," % d["tris"])
    lines.append("\t\tRoot = %s," % vec(fx["root"]))
    lines.append("\t\tHipHeight = %s," % num(fx["hip"]))
    lines.append("\t\tHitbox = { Radius = %s, Down = %s, Up = %s }," % tuple(num(x) for x in fx["hit"]))
    lines.append("\t\tJoints = {")
    for j in d["joints"]:
        anim = ('"%s"' % j["anim"]) if j["anim"] else "nil"
        lines.append('\t\t\t{ Name = "%s", Part = "%s", Parent = "%s", Pivot = %s, Rot = %s, Anim = %s },'
                     % (j["name"], j["part"], j["parent"], vec(j["pivot"]), vec(j["rot"]), anim))
    lines.append("\t\t},")
    lines.append("\t\tAttachments = {")
    for name, a in d["attachments"].items():
        lines.append('\t\t\t%s = { Part = "%s", Pos = %s },' % (name, a["part"], vec(a["pos"])))
    lines.append("\t\t},")
    lines.append("\t\tMeshes = {")
    for key, p in d["parts"].items():
        lines.append('\t\t\t%s = { Limb = "%s", Glow = %s },' % (key, p["limb"], "true" if p["glow"] else "false"))
    lines.append("\t\t},")
    lines.append("\t},")
lines.append("}")
open(OUT, "w").write("\n".join(lines) + "\n")
print("wrote", OUT)
